// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: resource/v1/resource.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResourceService_GetResourcesInChunk_FullMethodName  = "/resource.v1.ResourceService/GetResourcesInChunk"
	ResourceService_GetResourcesInChunks_FullMethodName = "/resource.v1.ResourceService/GetResourcesInChunks"
)

// ResourceServiceClient is the client API for ResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Resource related messages and services
type ResourceServiceClient interface {
	// Resource discovery operations
	GetResourcesInChunk(ctx context.Context, in *GetResourcesInChunkRequest, opts ...grpc.CallOption) (*GetResourcesInChunkResponse, error)
	GetResourcesInChunks(ctx context.Context, in *GetResourcesInChunksRequest, opts ...grpc.CallOption) (*GetResourcesInChunksResponse, error)
}

type resourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceServiceClient(cc grpc.ClientConnInterface) ResourceServiceClient {
	return &resourceServiceClient{cc}
}

func (c *resourceServiceClient) GetResourcesInChunk(ctx context.Context, in *GetResourcesInChunkRequest, opts ...grpc.CallOption) (*GetResourcesInChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResourcesInChunkResponse)
	err := c.cc.Invoke(ctx, ResourceService_GetResourcesInChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetResourcesInChunks(ctx context.Context, in *GetResourcesInChunksRequest, opts ...grpc.CallOption) (*GetResourcesInChunksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResourcesInChunksResponse)
	err := c.cc.Invoke(ctx, ResourceService_GetResourcesInChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceServiceServer is the server API for ResourceService service.
// All implementations must embed UnimplementedResourceServiceServer
// for forward compatibility.
//
// Resource related messages and services
type ResourceServiceServer interface {
	// Resource discovery operations
	GetResourcesInChunk(context.Context, *GetResourcesInChunkRequest) (*GetResourcesInChunkResponse, error)
	GetResourcesInChunks(context.Context, *GetResourcesInChunksRequest) (*GetResourcesInChunksResponse, error)
	mustEmbedUnimplementedResourceServiceServer()
}

// UnimplementedResourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResourceServiceServer struct{}

func (UnimplementedResourceServiceServer) GetResourcesInChunk(context.Context, *GetResourcesInChunkRequest) (*GetResourcesInChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResourcesInChunk not implemented")
}
func (UnimplementedResourceServiceServer) GetResourcesInChunks(context.Context, *GetResourcesInChunksRequest) (*GetResourcesInChunksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResourcesInChunks not implemented")
}
func (UnimplementedResourceServiceServer) mustEmbedUnimplementedResourceServiceServer() {}
func (UnimplementedResourceServiceServer) testEmbeddedByValue()                         {}

// UnsafeResourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceServiceServer will
// result in compilation errors.
type UnsafeResourceServiceServer interface {
	mustEmbedUnimplementedResourceServiceServer()
}

func RegisterResourceServiceServer(s grpc.ServiceRegistrar, srv ResourceServiceServer) {
	// If the following call pancis, it indicates UnimplementedResourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResourceService_ServiceDesc, srv)
}

func _ResourceService_GetResourcesInChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourcesInChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetResourcesInChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetResourcesInChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetResourcesInChunk(ctx, req.(*GetResourcesInChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetResourcesInChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourcesInChunksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetResourcesInChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetResourcesInChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetResourcesInChunks(ctx, req.(*GetResourcesInChunksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceService_ServiceDesc is the grpc.ServiceDesc for ResourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resource.v1.ResourceService",
	HandlerType: (*ResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetResourcesInChunk",
			Handler:    _ResourceService_GetResourcesInChunk_Handler,
		},
		{
			MethodName: "GetResourcesInChunks",
			Handler:    _ResourceService_GetResourcesInChunks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resource/v1/resource.proto",
}
