// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: character_actions/v1/character_actions.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CharacterActionsService_HarvestResource_FullMethodName = "/character_actions.v1.CharacterActionsService/HarvestResource"
)

// CharacterActionsServiceClient is the client API for CharacterActionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CharacterActionsServiceClient interface {
	// Resource harvesting
	HarvestResource(ctx context.Context, in *HarvestResourceRequest, opts ...grpc.CallOption) (*HarvestResourceResponse, error)
}

type characterActionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCharacterActionsServiceClient(cc grpc.ClientConnInterface) CharacterActionsServiceClient {
	return &characterActionsServiceClient{cc}
}

func (c *characterActionsServiceClient) HarvestResource(ctx context.Context, in *HarvestResourceRequest, opts ...grpc.CallOption) (*HarvestResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HarvestResourceResponse)
	err := c.cc.Invoke(ctx, CharacterActionsService_HarvestResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CharacterActionsServiceServer is the server API for CharacterActionsService service.
// All implementations must embed UnimplementedCharacterActionsServiceServer
// for forward compatibility.
type CharacterActionsServiceServer interface {
	// Resource harvesting
	HarvestResource(context.Context, *HarvestResourceRequest) (*HarvestResourceResponse, error)
	mustEmbedUnimplementedCharacterActionsServiceServer()
}

// UnimplementedCharacterActionsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCharacterActionsServiceServer struct{}

func (UnimplementedCharacterActionsServiceServer) HarvestResource(context.Context, *HarvestResourceRequest) (*HarvestResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HarvestResource not implemented")
}
func (UnimplementedCharacterActionsServiceServer) mustEmbedUnimplementedCharacterActionsServiceServer() {
}
func (UnimplementedCharacterActionsServiceServer) testEmbeddedByValue() {}

// UnsafeCharacterActionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CharacterActionsServiceServer will
// result in compilation errors.
type UnsafeCharacterActionsServiceServer interface {
	mustEmbedUnimplementedCharacterActionsServiceServer()
}

func RegisterCharacterActionsServiceServer(s grpc.ServiceRegistrar, srv CharacterActionsServiceServer) {
	// If the following call pancis, it indicates UnimplementedCharacterActionsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CharacterActionsService_ServiceDesc, srv)
}

func _CharacterActionsService_HarvestResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HarvestResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharacterActionsServiceServer).HarvestResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CharacterActionsService_HarvestResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharacterActionsServiceServer).HarvestResource(ctx, req.(*HarvestResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CharacterActionsService_ServiceDesc is the grpc.ServiceDesc for CharacterActionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CharacterActionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "character_actions.v1.CharacterActionsService",
	HandlerType: (*CharacterActionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HarvestResource",
			Handler:    _CharacterActionsService_HarvestResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "character_actions/v1/character_actions.proto",
}
