// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: character_actions/v1/character_actions.proto

package v1

import (
	v1 "github.com/VoidMesh/api/api/proto/inventory/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Harvest resource from a resource node
type HarvestResourceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CharacterId    string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	ResourceNodeId int32                  `protobuf:"varint,2,opt,name=resource_node_id,json=resourceNodeId,proto3" json:"resource_node_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HarvestResourceRequest) Reset() {
	*x = HarvestResourceRequest{}
	mi := &file_character_actions_v1_character_actions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarvestResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarvestResourceRequest) ProtoMessage() {}

func (x *HarvestResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_character_actions_v1_character_actions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarvestResourceRequest.ProtoReflect.Descriptor instead.
func (*HarvestResourceRequest) Descriptor() ([]byte, []int) {
	return file_character_actions_v1_character_actions_proto_rawDescGZIP(), []int{0}
}

func (x *HarvestResourceRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *HarvestResourceRequest) GetResourceNodeId() int32 {
	if x != nil {
		return x.ResourceNodeId
	}
	return 0
}

type HarvestResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Results       []*HarvestResult       `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	UpdatedItem   *v1.InventoryItem      `protobuf:"bytes,4,opt,name=updated_item,json=updatedItem,proto3" json:"updated_item,omitempty"` // Updated inventory item after harvest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarvestResourceResponse) Reset() {
	*x = HarvestResourceResponse{}
	mi := &file_character_actions_v1_character_actions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarvestResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarvestResourceResponse) ProtoMessage() {}

func (x *HarvestResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_character_actions_v1_character_actions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarvestResourceResponse.ProtoReflect.Descriptor instead.
func (*HarvestResourceResponse) Descriptor() ([]byte, []int) {
	return file_character_actions_v1_character_actions_proto_rawDescGZIP(), []int{1}
}

func (x *HarvestResourceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HarvestResourceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *HarvestResourceResponse) GetResults() []*HarvestResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *HarvestResourceResponse) GetUpdatedItem() *v1.InventoryItem {
	if x != nil {
		return x.UpdatedItem
	}
	return nil
}

type HarvestResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ItemName        string                 `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Quantity        int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	IsSecondaryDrop bool                   `protobuf:"varint,3,opt,name=is_secondary_drop,json=isSecondaryDrop,proto3" json:"is_secondary_drop,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HarvestResult) Reset() {
	*x = HarvestResult{}
	mi := &file_character_actions_v1_character_actions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarvestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarvestResult) ProtoMessage() {}

func (x *HarvestResult) ProtoReflect() protoreflect.Message {
	mi := &file_character_actions_v1_character_actions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarvestResult.ProtoReflect.Descriptor instead.
func (*HarvestResult) Descriptor() ([]byte, []int) {
	return file_character_actions_v1_character_actions_proto_rawDescGZIP(), []int{2}
}

func (x *HarvestResult) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *HarvestResult) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *HarvestResult) GetIsSecondaryDrop() bool {
	if x != nil {
		return x.IsSecondaryDrop
	}
	return false
}

var File_character_actions_v1_character_actions_proto protoreflect.FileDescriptor

const file_character_actions_v1_character_actions_proto_rawDesc = "" +
	"\n" +
	",character_actions/v1/character_actions.proto\x12\x14character_actions.v1\x1a\x1cinventory/v1/inventory.proto\"e\n" +
	"\x16HarvestResourceRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12(\n" +
	"\x10resource_node_id\x18\x02 \x01(\x05R\x0eresourceNodeId\"\xd7\x01\n" +
	"\x17HarvestResourceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12=\n" +
	"\aresults\x18\x03 \x03(\v2#.character_actions.v1.HarvestResultR\aresults\x12>\n" +
	"\fupdated_item\x18\x04 \x01(\v2\x1b.inventory.v1.InventoryItemR\vupdatedItem\"t\n" +
	"\rHarvestResult\x12\x1b\n" +
	"\titem_name\x18\x01 \x01(\tR\bitemName\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12*\n" +
	"\x11is_secondary_drop\x18\x03 \x01(\bR\x0fisSecondaryDrop2\x8b\x01\n" +
	"\x17CharacterActionsService\x12p\n" +
	"\x0fHarvestResource\x12,.character_actions.v1.HarvestResourceRequest\x1a-.character_actions.v1.HarvestResourceResponse\"\x00B8Z6github.com/VoidMesh/api/api/proto/character_actions/v1b\x06proto3"

var (
	file_character_actions_v1_character_actions_proto_rawDescOnce sync.Once
	file_character_actions_v1_character_actions_proto_rawDescData []byte
)

func file_character_actions_v1_character_actions_proto_rawDescGZIP() []byte {
	file_character_actions_v1_character_actions_proto_rawDescOnce.Do(func() {
		file_character_actions_v1_character_actions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_character_actions_v1_character_actions_proto_rawDesc), len(file_character_actions_v1_character_actions_proto_rawDesc)))
	})
	return file_character_actions_v1_character_actions_proto_rawDescData
}

var file_character_actions_v1_character_actions_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_character_actions_v1_character_actions_proto_goTypes = []any{
	(*HarvestResourceRequest)(nil),  // 0: character_actions.v1.HarvestResourceRequest
	(*HarvestResourceResponse)(nil), // 1: character_actions.v1.HarvestResourceResponse
	(*HarvestResult)(nil),           // 2: character_actions.v1.HarvestResult
	(*v1.InventoryItem)(nil),        // 3: inventory.v1.InventoryItem
}
var file_character_actions_v1_character_actions_proto_depIdxs = []int32{
	2, // 0: character_actions.v1.HarvestResourceResponse.results:type_name -> character_actions.v1.HarvestResult
	3, // 1: character_actions.v1.HarvestResourceResponse.updated_item:type_name -> inventory.v1.InventoryItem
	0, // 2: character_actions.v1.CharacterActionsService.HarvestResource:input_type -> character_actions.v1.HarvestResourceRequest
	1, // 3: character_actions.v1.CharacterActionsService.HarvestResource:output_type -> character_actions.v1.HarvestResourceResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_character_actions_v1_character_actions_proto_init() }
func file_character_actions_v1_character_actions_proto_init() {
	if File_character_actions_v1_character_actions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_character_actions_v1_character_actions_proto_rawDesc), len(file_character_actions_v1_character_actions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_character_actions_v1_character_actions_proto_goTypes,
		DependencyIndexes: file_character_actions_v1_character_actions_proto_depIdxs,
		MessageInfos:      file_character_actions_v1_character_actions_proto_msgTypes,
	}.Build()
	File_character_actions_v1_character_actions_proto = out.File
	file_character_actions_v1_character_actions_proto_goTypes = nil
	file_character_actions_v1_character_actions_proto_depIdxs = nil
}
