// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: terrain/v1/terrain.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TerrainService_GetTerrainTypes_FullMethodName = "/terrain.v1.TerrainService/GetTerrainTypes"
)

// TerrainServiceClient is the client API for TerrainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Terrain related messages and services
type TerrainServiceClient interface {
	// Get all terrain types
	GetTerrainTypes(ctx context.Context, in *GetTerrainTypesRequest, opts ...grpc.CallOption) (*GetTerrainTypesResponse, error)
}

type terrainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTerrainServiceClient(cc grpc.ClientConnInterface) TerrainServiceClient {
	return &terrainServiceClient{cc}
}

func (c *terrainServiceClient) GetTerrainTypes(ctx context.Context, in *GetTerrainTypesRequest, opts ...grpc.CallOption) (*GetTerrainTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTerrainTypesResponse)
	err := c.cc.Invoke(ctx, TerrainService_GetTerrainTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TerrainServiceServer is the server API for TerrainService service.
// All implementations must embed UnimplementedTerrainServiceServer
// for forward compatibility.
//
// Terrain related messages and services
type TerrainServiceServer interface {
	// Get all terrain types
	GetTerrainTypes(context.Context, *GetTerrainTypesRequest) (*GetTerrainTypesResponse, error)
	mustEmbedUnimplementedTerrainServiceServer()
}

// UnimplementedTerrainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTerrainServiceServer struct{}

func (UnimplementedTerrainServiceServer) GetTerrainTypes(context.Context, *GetTerrainTypesRequest) (*GetTerrainTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTerrainTypes not implemented")
}
func (UnimplementedTerrainServiceServer) mustEmbedUnimplementedTerrainServiceServer() {}
func (UnimplementedTerrainServiceServer) testEmbeddedByValue()                        {}

// UnsafeTerrainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TerrainServiceServer will
// result in compilation errors.
type UnsafeTerrainServiceServer interface {
	mustEmbedUnimplementedTerrainServiceServer()
}

func RegisterTerrainServiceServer(s grpc.ServiceRegistrar, srv TerrainServiceServer) {
	// If the following call pancis, it indicates UnimplementedTerrainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TerrainService_ServiceDesc, srv)
}

func _TerrainService_GetTerrainTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTerrainTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerrainServiceServer).GetTerrainTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerrainService_GetTerrainTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerrainServiceServer).GetTerrainTypes(ctx, req.(*GetTerrainTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TerrainService_ServiceDesc is the grpc.ServiceDesc for TerrainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TerrainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "terrain.v1.TerrainService",
	HandlerType: (*TerrainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTerrainTypes",
			Handler:    _TerrainService_GetTerrainTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "terrain/v1/terrain.proto",
}
