// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: terrain/v1/terrain.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Terrain types match those defined in chunk.proto
type TerrainType int32

const (
	TerrainType_TERRAIN_TYPE_UNSPECIFIED TerrainType = 0
	TerrainType_TERRAIN_TYPE_GRASS       TerrainType = 1
	TerrainType_TERRAIN_TYPE_WATER       TerrainType = 2
	TerrainType_TERRAIN_TYPE_STONE       TerrainType = 3
	TerrainType_TERRAIN_TYPE_SAND        TerrainType = 4
	TerrainType_TERRAIN_TYPE_DIRT        TerrainType = 5
)

// Enum value maps for TerrainType.
var (
	TerrainType_name = map[int32]string{
		0: "TERRAIN_TYPE_UNSPECIFIED",
		1: "TERRAIN_TYPE_GRASS",
		2: "TERRAIN_TYPE_WATER",
		3: "TERRAIN_TYPE_STONE",
		4: "TERRAIN_TYPE_SAND",
		5: "TERRAIN_TYPE_DIRT",
	}
	TerrainType_value = map[string]int32{
		"TERRAIN_TYPE_UNSPECIFIED": 0,
		"TERRAIN_TYPE_GRASS":       1,
		"TERRAIN_TYPE_WATER":       2,
		"TERRAIN_TYPE_STONE":       3,
		"TERRAIN_TYPE_SAND":        4,
		"TERRAIN_TYPE_DIRT":        5,
	}
)

func (x TerrainType) Enum() *TerrainType {
	p := new(TerrainType)
	*p = x
	return p
}

func (x TerrainType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerrainType) Descriptor() protoreflect.EnumDescriptor {
	return file_terrain_v1_terrain_proto_enumTypes[0].Descriptor()
}

func (TerrainType) Type() protoreflect.EnumType {
	return &file_terrain_v1_terrain_proto_enumTypes[0]
}

func (x TerrainType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TerrainType.Descriptor instead.
func (TerrainType) EnumDescriptor() ([]byte, []int) {
	return file_terrain_v1_terrain_proto_rawDescGZIP(), []int{0}
}

// Terrain type properties
type TerrainTypeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          TerrainType            `protobuf:"varint,1,opt,name=type,proto3,enum=terrain.v1.TerrainType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Visual        *TerrainVisual         `protobuf:"bytes,4,opt,name=visual,proto3" json:"visual,omitempty"`
	Properties    *TerrainProperties     `protobuf:"bytes,5,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerrainTypeInfo) Reset() {
	*x = TerrainTypeInfo{}
	mi := &file_terrain_v1_terrain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerrainTypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerrainTypeInfo) ProtoMessage() {}

func (x *TerrainTypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_terrain_v1_terrain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerrainTypeInfo.ProtoReflect.Descriptor instead.
func (*TerrainTypeInfo) Descriptor() ([]byte, []int) {
	return file_terrain_v1_terrain_proto_rawDescGZIP(), []int{0}
}

func (x *TerrainTypeInfo) GetType() TerrainType {
	if x != nil {
		return x.Type
	}
	return TerrainType_TERRAIN_TYPE_UNSPECIFIED
}

func (x *TerrainTypeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TerrainTypeInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TerrainTypeInfo) GetVisual() *TerrainVisual {
	if x != nil {
		return x.Visual
	}
	return nil
}

func (x *TerrainTypeInfo) GetProperties() *TerrainProperties {
	if x != nil {
		return x.Properties
	}
	return nil
}

// Visual properties of terrain
type TerrainVisual struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseColor     string                 `protobuf:"bytes,1,opt,name=base_color,json=baseColor,proto3" json:"base_color,omitempty"`
	Texture       string                 `protobuf:"bytes,2,opt,name=texture,proto3" json:"texture,omitempty"`
	Roughness     float32                `protobuf:"fixed32,3,opt,name=roughness,proto3" json:"roughness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerrainVisual) Reset() {
	*x = TerrainVisual{}
	mi := &file_terrain_v1_terrain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerrainVisual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerrainVisual) ProtoMessage() {}

func (x *TerrainVisual) ProtoReflect() protoreflect.Message {
	mi := &file_terrain_v1_terrain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerrainVisual.ProtoReflect.Descriptor instead.
func (*TerrainVisual) Descriptor() ([]byte, []int) {
	return file_terrain_v1_terrain_proto_rawDescGZIP(), []int{1}
}

func (x *TerrainVisual) GetBaseColor() string {
	if x != nil {
		return x.BaseColor
	}
	return ""
}

func (x *TerrainVisual) GetTexture() string {
	if x != nil {
		return x.Texture
	}
	return ""
}

func (x *TerrainVisual) GetRoughness() float32 {
	if x != nil {
		return x.Roughness
	}
	return 0
}

// Physical properties of terrain
type TerrainProperties struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	MovementSpeedMultiplier float32                `protobuf:"fixed32,1,opt,name=movement_speed_multiplier,json=movementSpeedMultiplier,proto3" json:"movement_speed_multiplier,omitempty"`
	IsWater                 bool                   `protobuf:"varint,2,opt,name=is_water,json=isWater,proto3" json:"is_water,omitempty"`
	IsPassable              bool                   `protobuf:"varint,3,opt,name=is_passable,json=isPassable,proto3" json:"is_passable,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TerrainProperties) Reset() {
	*x = TerrainProperties{}
	mi := &file_terrain_v1_terrain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerrainProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerrainProperties) ProtoMessage() {}

func (x *TerrainProperties) ProtoReflect() protoreflect.Message {
	mi := &file_terrain_v1_terrain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerrainProperties.ProtoReflect.Descriptor instead.
func (*TerrainProperties) Descriptor() ([]byte, []int) {
	return file_terrain_v1_terrain_proto_rawDescGZIP(), []int{2}
}

func (x *TerrainProperties) GetMovementSpeedMultiplier() float32 {
	if x != nil {
		return x.MovementSpeedMultiplier
	}
	return 0
}

func (x *TerrainProperties) GetIsWater() bool {
	if x != nil {
		return x.IsWater
	}
	return false
}

func (x *TerrainProperties) GetIsPassable() bool {
	if x != nil {
		return x.IsPassable
	}
	return false
}

// Request to get all terrain types
type GetTerrainTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTerrainTypesRequest) Reset() {
	*x = GetTerrainTypesRequest{}
	mi := &file_terrain_v1_terrain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTerrainTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTerrainTypesRequest) ProtoMessage() {}

func (x *GetTerrainTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrain_v1_terrain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTerrainTypesRequest.ProtoReflect.Descriptor instead.
func (*GetTerrainTypesRequest) Descriptor() ([]byte, []int) {
	return file_terrain_v1_terrain_proto_rawDescGZIP(), []int{3}
}

// Response with all terrain types
type GetTerrainTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TerrainTypes  []*TerrainTypeInfo     `protobuf:"bytes,1,rep,name=terrain_types,json=terrainTypes,proto3" json:"terrain_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTerrainTypesResponse) Reset() {
	*x = GetTerrainTypesResponse{}
	mi := &file_terrain_v1_terrain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTerrainTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTerrainTypesResponse) ProtoMessage() {}

func (x *GetTerrainTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrain_v1_terrain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTerrainTypesResponse.ProtoReflect.Descriptor instead.
func (*GetTerrainTypesResponse) Descriptor() ([]byte, []int) {
	return file_terrain_v1_terrain_proto_rawDescGZIP(), []int{4}
}

func (x *GetTerrainTypesResponse) GetTerrainTypes() []*TerrainTypeInfo {
	if x != nil {
		return x.TerrainTypes
	}
	return nil
}

var File_terrain_v1_terrain_proto protoreflect.FileDescriptor

const file_terrain_v1_terrain_proto_rawDesc = "" +
	"\n" +
	"\x18terrain/v1/terrain.proto\x12\n" +
	"terrain.v1\"\xe6\x01\n" +
	"\x0fTerrainTypeInfo\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.terrain.v1.TerrainTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x121\n" +
	"\x06visual\x18\x04 \x01(\v2\x19.terrain.v1.TerrainVisualR\x06visual\x12=\n" +
	"\n" +
	"properties\x18\x05 \x01(\v2\x1d.terrain.v1.TerrainPropertiesR\n" +
	"properties\"f\n" +
	"\rTerrainVisual\x12\x1d\n" +
	"\n" +
	"base_color\x18\x01 \x01(\tR\tbaseColor\x12\x18\n" +
	"\atexture\x18\x02 \x01(\tR\atexture\x12\x1c\n" +
	"\troughness\x18\x03 \x01(\x02R\troughness\"\x8b\x01\n" +
	"\x11TerrainProperties\x12:\n" +
	"\x19movement_speed_multiplier\x18\x01 \x01(\x02R\x17movementSpeedMultiplier\x12\x19\n" +
	"\bis_water\x18\x02 \x01(\bR\aisWater\x12\x1f\n" +
	"\vis_passable\x18\x03 \x01(\bR\n" +
	"isPassable\"\x18\n" +
	"\x16GetTerrainTypesRequest\"[\n" +
	"\x17GetTerrainTypesResponse\x12@\n" +
	"\rterrain_types\x18\x01 \x03(\v2\x1b.terrain.v1.TerrainTypeInfoR\fterrainTypes*\xa1\x01\n" +
	"\vTerrainType\x12\x1c\n" +
	"\x18TERRAIN_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TERRAIN_TYPE_GRASS\x10\x01\x12\x16\n" +
	"\x12TERRAIN_TYPE_WATER\x10\x02\x12\x16\n" +
	"\x12TERRAIN_TYPE_STONE\x10\x03\x12\x15\n" +
	"\x11TERRAIN_TYPE_SAND\x10\x04\x12\x15\n" +
	"\x11TERRAIN_TYPE_DIRT\x10\x052n\n" +
	"\x0eTerrainService\x12\\\n" +
	"\x0fGetTerrainTypes\x12\".terrain.v1.GetTerrainTypesRequest\x1a#.terrain.v1.GetTerrainTypesResponse\"\x00B.Z,github.com/VoidMesh/api/api/proto/terrain/v1b\x06proto3"

var (
	file_terrain_v1_terrain_proto_rawDescOnce sync.Once
	file_terrain_v1_terrain_proto_rawDescData []byte
)

func file_terrain_v1_terrain_proto_rawDescGZIP() []byte {
	file_terrain_v1_terrain_proto_rawDescOnce.Do(func() {
		file_terrain_v1_terrain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_terrain_v1_terrain_proto_rawDesc), len(file_terrain_v1_terrain_proto_rawDesc)))
	})
	return file_terrain_v1_terrain_proto_rawDescData
}

var file_terrain_v1_terrain_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_terrain_v1_terrain_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_terrain_v1_terrain_proto_goTypes = []any{
	(TerrainType)(0),                // 0: terrain.v1.TerrainType
	(*TerrainTypeInfo)(nil),         // 1: terrain.v1.TerrainTypeInfo
	(*TerrainVisual)(nil),           // 2: terrain.v1.TerrainVisual
	(*TerrainProperties)(nil),       // 3: terrain.v1.TerrainProperties
	(*GetTerrainTypesRequest)(nil),  // 4: terrain.v1.GetTerrainTypesRequest
	(*GetTerrainTypesResponse)(nil), // 5: terrain.v1.GetTerrainTypesResponse
}
var file_terrain_v1_terrain_proto_depIdxs = []int32{
	0, // 0: terrain.v1.TerrainTypeInfo.type:type_name -> terrain.v1.TerrainType
	2, // 1: terrain.v1.TerrainTypeInfo.visual:type_name -> terrain.v1.TerrainVisual
	3, // 2: terrain.v1.TerrainTypeInfo.properties:type_name -> terrain.v1.TerrainProperties
	1, // 3: terrain.v1.GetTerrainTypesResponse.terrain_types:type_name -> terrain.v1.TerrainTypeInfo
	4, // 4: terrain.v1.TerrainService.GetTerrainTypes:input_type -> terrain.v1.GetTerrainTypesRequest
	5, // 5: terrain.v1.TerrainService.GetTerrainTypes:output_type -> terrain.v1.GetTerrainTypesResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_terrain_v1_terrain_proto_init() }
func file_terrain_v1_terrain_proto_init() {
	if File_terrain_v1_terrain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_terrain_v1_terrain_proto_rawDesc), len(file_terrain_v1_terrain_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_terrain_v1_terrain_proto_goTypes,
		DependencyIndexes: file_terrain_v1_terrain_proto_depIdxs,
		EnumInfos:         file_terrain_v1_terrain_proto_enumTypes,
		MessageInfos:      file_terrain_v1_terrain_proto_msgTypes,
	}.Build()
	File_terrain_v1_terrain_proto = out.File
	file_terrain_v1_terrain_proto_goTypes = nil
	file_terrain_v1_terrain_proto_depIdxs = nil
}
