// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: inventory/v1/inventory.proto

package v1

import (
	v1 "github.com/VoidMesh/api/api/proto/resource_node/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Inventory item representing a resource in character's inventory
type InventoryItem struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CharacterId        string                 `protobuf:"bytes,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	ResourceNodeTypeId v1.ResourceNodeTypeId  `protobuf:"varint,3,opt,name=resource_node_type_id,json=resourceNodeTypeId,proto3,enum=resource_node.v1.ResourceNodeTypeId" json:"resource_node_type_id,omitempty"`
	ResourceNodeType   *v1.ResourceNodeType   `protobuf:"bytes,4,opt,name=resource_node_type,json=resourceNodeType,proto3" json:"resource_node_type,omitempty"` // Populated for display
	Quantity           int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *InventoryItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InventoryItem) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *InventoryItem) GetResourceNodeTypeId() v1.ResourceNodeTypeId {
	if x != nil {
		return x.ResourceNodeTypeId
	}
	return v1.ResourceNodeTypeId(0)
}

func (x *InventoryItem) GetResourceNodeType() *v1.ResourceNodeType {
	if x != nil {
		return x.ResourceNodeType
	}
	return nil
}

func (x *InventoryItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *InventoryItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *InventoryItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Get character inventory
type GetCharacterInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterInventoryRequest) Reset() {
	*x = GetCharacterInventoryRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterInventoryRequest) ProtoMessage() {}

func (x *GetCharacterInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterInventoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GetCharacterInventoryRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

type GetCharacterInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*InventoryItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalItems    int32                  `protobuf:"varint,2,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterInventoryResponse) Reset() {
	*x = GetCharacterInventoryResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterInventoryResponse) ProtoMessage() {}

func (x *GetCharacterInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetCharacterInventoryResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetCharacterInventoryResponse) GetItems() []*InventoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetCharacterInventoryResponse) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

// Harvest resource node
type HarvestResourceNodeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CharacterId    string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	ResourceNodeId int32                  `protobuf:"varint,2,opt,name=resource_node_id,json=resourceNodeId,proto3" json:"resource_node_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HarvestResourceNodeRequest) Reset() {
	*x = HarvestResourceNodeRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarvestResourceNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarvestResourceNodeRequest) ProtoMessage() {}

func (x *HarvestResourceNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarvestResourceNodeRequest.ProtoReflect.Descriptor instead.
func (*HarvestResourceNodeRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *HarvestResourceNodeRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *HarvestResourceNodeRequest) GetResourceNodeId() int32 {
	if x != nil {
		return x.ResourceNodeId
	}
	return 0
}

type HarvestResourceNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Results       []*HarvestResult       `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	UpdatedItem   *InventoryItem         `protobuf:"bytes,4,opt,name=updated_item,json=updatedItem,proto3" json:"updated_item,omitempty"` // Updated inventory item after harvest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarvestResourceNodeResponse) Reset() {
	*x = HarvestResourceNodeResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarvestResourceNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarvestResourceNodeResponse) ProtoMessage() {}

func (x *HarvestResourceNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarvestResourceNodeResponse.ProtoReflect.Descriptor instead.
func (*HarvestResourceNodeResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *HarvestResourceNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HarvestResourceNodeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *HarvestResourceNodeResponse) GetResults() []*HarvestResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *HarvestResourceNodeResponse) GetUpdatedItem() *InventoryItem {
	if x != nil {
		return x.UpdatedItem
	}
	return nil
}

type HarvestResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ItemName        string                 `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Quantity        int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	IsSecondaryDrop bool                   `protobuf:"varint,3,opt,name=is_secondary_drop,json=isSecondaryDrop,proto3" json:"is_secondary_drop,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HarvestResult) Reset() {
	*x = HarvestResult{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarvestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarvestResult) ProtoMessage() {}

func (x *HarvestResult) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarvestResult.ProtoReflect.Descriptor instead.
func (*HarvestResult) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *HarvestResult) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *HarvestResult) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *HarvestResult) GetIsSecondaryDrop() bool {
	if x != nil {
		return x.IsSecondaryDrop
	}
	return false
}

// Add inventory item
type AddInventoryItemRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CharacterId        string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	ResourceNodeTypeId v1.ResourceNodeTypeId  `protobuf:"varint,2,opt,name=resource_node_type_id,json=resourceNodeTypeId,proto3,enum=resource_node.v1.ResourceNodeTypeId" json:"resource_node_type_id,omitempty"`
	Quantity           int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AddInventoryItemRequest) Reset() {
	*x = AddInventoryItemRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddInventoryItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInventoryItemRequest) ProtoMessage() {}

func (x *AddInventoryItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInventoryItemRequest.ProtoReflect.Descriptor instead.
func (*AddInventoryItemRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *AddInventoryItemRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *AddInventoryItemRequest) GetResourceNodeTypeId() v1.ResourceNodeTypeId {
	if x != nil {
		return x.ResourceNodeTypeId
	}
	return v1.ResourceNodeTypeId(0)
}

func (x *AddInventoryItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AddInventoryItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *InventoryItem         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddInventoryItemResponse) Reset() {
	*x = AddInventoryItemResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddInventoryItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInventoryItemResponse) ProtoMessage() {}

func (x *AddInventoryItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInventoryItemResponse.ProtoReflect.Descriptor instead.
func (*AddInventoryItemResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *AddInventoryItemResponse) GetItem() *InventoryItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *AddInventoryItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddInventoryItemResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Remove inventory item
type RemoveInventoryItemRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CharacterId        string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	ResourceNodeTypeId v1.ResourceNodeTypeId  `protobuf:"varint,2,opt,name=resource_node_type_id,json=resourceNodeTypeId,proto3,enum=resource_node.v1.ResourceNodeTypeId" json:"resource_node_type_id,omitempty"`
	Quantity           int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RemoveInventoryItemRequest) Reset() {
	*x = RemoveInventoryItemRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveInventoryItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveInventoryItemRequest) ProtoMessage() {}

func (x *RemoveInventoryItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveInventoryItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveInventoryItemRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveInventoryItemRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *RemoveInventoryItemRequest) GetResourceNodeTypeId() v1.ResourceNodeTypeId {
	if x != nil {
		return x.ResourceNodeTypeId
	}
	return v1.ResourceNodeTypeId(0)
}

func (x *RemoveInventoryItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type RemoveInventoryItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *InventoryItem         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"` // Updated item, null if completely removed
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveInventoryItemResponse) Reset() {
	*x = RemoveInventoryItemResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveInventoryItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveInventoryItemResponse) ProtoMessage() {}

func (x *RemoveInventoryItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveInventoryItemResponse.ProtoReflect.Descriptor instead.
func (*RemoveInventoryItemResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveInventoryItemResponse) GetItem() *InventoryItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *RemoveInventoryItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveInventoryItemResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Update item quantity
type UpdateItemQuantityRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CharacterId        string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	ResourceNodeTypeId v1.ResourceNodeTypeId  `protobuf:"varint,2,opt,name=resource_node_type_id,json=resourceNodeTypeId,proto3,enum=resource_node.v1.ResourceNodeTypeId" json:"resource_node_type_id,omitempty"`
	NewQuantity        int32                  `protobuf:"varint,3,opt,name=new_quantity,json=newQuantity,proto3" json:"new_quantity,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateItemQuantityRequest) Reset() {
	*x = UpdateItemQuantityRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemQuantityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemQuantityRequest) ProtoMessage() {}

func (x *UpdateItemQuantityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemQuantityRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemQuantityRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateItemQuantityRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *UpdateItemQuantityRequest) GetResourceNodeTypeId() v1.ResourceNodeTypeId {
	if x != nil {
		return x.ResourceNodeTypeId
	}
	return v1.ResourceNodeTypeId(0)
}

func (x *UpdateItemQuantityRequest) GetNewQuantity() int32 {
	if x != nil {
		return x.NewQuantity
	}
	return 0
}

type UpdateItemQuantityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *InventoryItem         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemQuantityResponse) Reset() {
	*x = UpdateItemQuantityResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemQuantityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemQuantityResponse) ProtoMessage() {}

func (x *UpdateItemQuantityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemQuantityResponse.ProtoReflect.Descriptor instead.
func (*UpdateItemQuantityResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateItemQuantityResponse) GetItem() *InventoryItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *UpdateItemQuantityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateItemQuantityResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1cinventory/v1/inventory.proto\x12\finventory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$resource_node/v1/resource_node.proto\"\xff\x02\n" +
	"\rInventoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12!\n" +
	"\fcharacter_id\x18\x02 \x01(\tR\vcharacterId\x12W\n" +
	"\x15resource_node_type_id\x18\x03 \x01(\x0e2$.resource_node.v1.ResourceNodeTypeIdR\x12resourceNodeTypeId\x12P\n" +
	"\x12resource_node_type\x18\x04 \x01(\v2\".resource_node.v1.ResourceNodeTypeR\x10resourceNodeType\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"A\n" +
	"\x1cGetCharacterInventoryRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\"s\n" +
	"\x1dGetCharacterInventoryResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.inventory.v1.InventoryItemR\x05items\x12\x1f\n" +
	"\vtotal_items\x18\x02 \x01(\x05R\n" +
	"totalItems\"i\n" +
	"\x1aHarvestResourceNodeRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12(\n" +
	"\x10resource_node_id\x18\x02 \x01(\x05R\x0eresourceNodeId\"\xd3\x01\n" +
	"\x1bHarvestResourceNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x125\n" +
	"\aresults\x18\x03 \x03(\v2\x1b.inventory.v1.HarvestResultR\aresults\x12>\n" +
	"\fupdated_item\x18\x04 \x01(\v2\x1b.inventory.v1.InventoryItemR\vupdatedItem\"t\n" +
	"\rHarvestResult\x12\x1b\n" +
	"\titem_name\x18\x01 \x01(\tR\bitemName\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12*\n" +
	"\x11is_secondary_drop\x18\x03 \x01(\bR\x0fisSecondaryDrop\"\xb1\x01\n" +
	"\x17AddInventoryItemRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12W\n" +
	"\x15resource_node_type_id\x18\x02 \x01(\x0e2$.resource_node.v1.ResourceNodeTypeIdR\x12resourceNodeTypeId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"\x8a\x01\n" +
	"\x18AddInventoryItemResponse\x12/\n" +
	"\x04item\x18\x01 \x01(\v2\x1b.inventory.v1.InventoryItemR\x04item\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xb4\x01\n" +
	"\x1aRemoveInventoryItemRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12W\n" +
	"\x15resource_node_type_id\x18\x02 \x01(\x0e2$.resource_node.v1.ResourceNodeTypeIdR\x12resourceNodeTypeId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"\x8d\x01\n" +
	"\x1bRemoveInventoryItemResponse\x12/\n" +
	"\x04item\x18\x01 \x01(\v2\x1b.inventory.v1.InventoryItemR\x04item\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xba\x01\n" +
	"\x19UpdateItemQuantityRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12W\n" +
	"\x15resource_node_type_id\x18\x02 \x01(\x0e2$.resource_node.v1.ResourceNodeTypeIdR\x12resourceNodeTypeId\x12!\n" +
	"\fnew_quantity\x18\x03 \x01(\x05R\vnewQuantity\"\x8c\x01\n" +
	"\x1aUpdateItemQuantityResponse\x12/\n" +
	"\x04item\x18\x01 \x01(\v2\x1b.inventory.v1.InventoryItemR\x04item\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2\xb2\x04\n" +
	"\x10InventoryService\x12r\n" +
	"\x15GetCharacterInventory\x12*.inventory.v1.GetCharacterInventoryRequest\x1a+.inventory.v1.GetCharacterInventoryResponse\"\x00\x12l\n" +
	"\x13HarvestResourceNode\x12(.inventory.v1.HarvestResourceNodeRequest\x1a).inventory.v1.HarvestResourceNodeResponse\"\x00\x12c\n" +
	"\x10AddInventoryItem\x12%.inventory.v1.AddInventoryItemRequest\x1a&.inventory.v1.AddInventoryItemResponse\"\x00\x12l\n" +
	"\x13RemoveInventoryItem\x12(.inventory.v1.RemoveInventoryItemRequest\x1a).inventory.v1.RemoveInventoryItemResponse\"\x00\x12i\n" +
	"\x12UpdateItemQuantity\x12'.inventory.v1.UpdateItemQuantityRequest\x1a(.inventory.v1.UpdateItemQuantityResponse\"\x00B0Z.github.com/VoidMesh/api/api/proto/inventory/v1b\x06proto3"

var (
	file_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_inventory_v1_inventory_proto_rawDescData []byte
)

func file_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_inventory_v1_inventory_proto_rawDescData
}

var file_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_inventory_v1_inventory_proto_goTypes = []any{
	(*InventoryItem)(nil),                 // 0: inventory.v1.InventoryItem
	(*GetCharacterInventoryRequest)(nil),  // 1: inventory.v1.GetCharacterInventoryRequest
	(*GetCharacterInventoryResponse)(nil), // 2: inventory.v1.GetCharacterInventoryResponse
	(*HarvestResourceNodeRequest)(nil),    // 3: inventory.v1.HarvestResourceNodeRequest
	(*HarvestResourceNodeResponse)(nil),   // 4: inventory.v1.HarvestResourceNodeResponse
	(*HarvestResult)(nil),                 // 5: inventory.v1.HarvestResult
	(*AddInventoryItemRequest)(nil),       // 6: inventory.v1.AddInventoryItemRequest
	(*AddInventoryItemResponse)(nil),      // 7: inventory.v1.AddInventoryItemResponse
	(*RemoveInventoryItemRequest)(nil),    // 8: inventory.v1.RemoveInventoryItemRequest
	(*RemoveInventoryItemResponse)(nil),   // 9: inventory.v1.RemoveInventoryItemResponse
	(*UpdateItemQuantityRequest)(nil),     // 10: inventory.v1.UpdateItemQuantityRequest
	(*UpdateItemQuantityResponse)(nil),    // 11: inventory.v1.UpdateItemQuantityResponse
	(v1.ResourceNodeTypeId)(0),            // 12: resource_node.v1.ResourceNodeTypeId
	(*v1.ResourceNodeType)(nil),           // 13: resource_node.v1.ResourceNodeType
	(*timestamppb.Timestamp)(nil),         // 14: google.protobuf.Timestamp
}
var file_inventory_v1_inventory_proto_depIdxs = []int32{
	12, // 0: inventory.v1.InventoryItem.resource_node_type_id:type_name -> resource_node.v1.ResourceNodeTypeId
	13, // 1: inventory.v1.InventoryItem.resource_node_type:type_name -> resource_node.v1.ResourceNodeType
	14, // 2: inventory.v1.InventoryItem.created_at:type_name -> google.protobuf.Timestamp
	14, // 3: inventory.v1.InventoryItem.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: inventory.v1.GetCharacterInventoryResponse.items:type_name -> inventory.v1.InventoryItem
	5,  // 5: inventory.v1.HarvestResourceNodeResponse.results:type_name -> inventory.v1.HarvestResult
	0,  // 6: inventory.v1.HarvestResourceNodeResponse.updated_item:type_name -> inventory.v1.InventoryItem
	12, // 7: inventory.v1.AddInventoryItemRequest.resource_node_type_id:type_name -> resource_node.v1.ResourceNodeTypeId
	0,  // 8: inventory.v1.AddInventoryItemResponse.item:type_name -> inventory.v1.InventoryItem
	12, // 9: inventory.v1.RemoveInventoryItemRequest.resource_node_type_id:type_name -> resource_node.v1.ResourceNodeTypeId
	0,  // 10: inventory.v1.RemoveInventoryItemResponse.item:type_name -> inventory.v1.InventoryItem
	12, // 11: inventory.v1.UpdateItemQuantityRequest.resource_node_type_id:type_name -> resource_node.v1.ResourceNodeTypeId
	0,  // 12: inventory.v1.UpdateItemQuantityResponse.item:type_name -> inventory.v1.InventoryItem
	1,  // 13: inventory.v1.InventoryService.GetCharacterInventory:input_type -> inventory.v1.GetCharacterInventoryRequest
	3,  // 14: inventory.v1.InventoryService.HarvestResourceNode:input_type -> inventory.v1.HarvestResourceNodeRequest
	6,  // 15: inventory.v1.InventoryService.AddInventoryItem:input_type -> inventory.v1.AddInventoryItemRequest
	8,  // 16: inventory.v1.InventoryService.RemoveInventoryItem:input_type -> inventory.v1.RemoveInventoryItemRequest
	10, // 17: inventory.v1.InventoryService.UpdateItemQuantity:input_type -> inventory.v1.UpdateItemQuantityRequest
	2,  // 18: inventory.v1.InventoryService.GetCharacterInventory:output_type -> inventory.v1.GetCharacterInventoryResponse
	4,  // 19: inventory.v1.InventoryService.HarvestResourceNode:output_type -> inventory.v1.HarvestResourceNodeResponse
	7,  // 20: inventory.v1.InventoryService.AddInventoryItem:output_type -> inventory.v1.AddInventoryItemResponse
	9,  // 21: inventory.v1.InventoryService.RemoveInventoryItem:output_type -> inventory.v1.RemoveInventoryItemResponse
	11, // 22: inventory.v1.InventoryService.UpdateItemQuantity:output_type -> inventory.v1.UpdateItemQuantityResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_inventory_v1_inventory_proto_init() }
func file_inventory_v1_inventory_proto_init() {
	if File_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_v1_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_inventory_v1_inventory_proto = out.File
	file_inventory_v1_inventory_proto_goTypes = nil
	file_inventory_v1_inventory_proto_depIdxs = nil
}
