// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Chunk struct {
	ChunkX       int64        `json:"chunk_x"`
	ChunkZ       int64        `json:"chunk_z"`
	CreatedAt    sql.NullTime `json:"created_at"`
	LastModified sql.NullTime `json:"last_modified"`
}

type HarvestLog struct {
	LogID           int64        `json:"log_id"`
	NodeID          int64        `json:"node_id"`
	PlayerID        int64        `json:"player_id"`
	AmountHarvested int64        `json:"amount_harvested"`
	HarvestedAt     sql.NullTime `json:"harvested_at"`
	NodeYieldBefore int64        `json:"node_yield_before"`
	NodeYieldAfter  int64        `json:"node_yield_after"`
}

type HarvestSession struct {
	SessionID         int64         `json:"session_id"`
	NodeID            int64         `json:"node_id"`
	PlayerID          int64         `json:"player_id"`
	StartedAt         sql.NullTime  `json:"started_at"`
	LastActivity      sql.NullTime  `json:"last_activity"`
	ResourcesGathered sql.NullInt64 `json:"resources_gathered"`
}

type NodeSpawnTemplate struct {
	TemplateID        int64          `json:"template_id"`
	NodeType          int64          `json:"node_type"`
	NodeSubtype       sql.NullInt64  `json:"node_subtype"`
	SpawnType         int64          `json:"spawn_type"`
	MinYield          int64          `json:"min_yield"`
	MaxYield          int64          `json:"max_yield"`
	RegenerationRate  sql.NullInt64  `json:"regeneration_rate"`
	RespawnDelayHours sql.NullInt64  `json:"respawn_delay_hours"`
	SpawnWeight       sql.NullInt64  `json:"spawn_weight"`
	BiomeRestriction  sql.NullString `json:"biome_restriction"`
}

type ResourceNode struct {
	NodeID           int64         `json:"node_id"`
	ChunkX           int64         `json:"chunk_x"`
	ChunkZ           int64         `json:"chunk_z"`
	LocalX           int64         `json:"local_x"`
	LocalZ           int64         `json:"local_z"`
	NodeType         int64         `json:"node_type"`
	NodeSubtype      sql.NullInt64 `json:"node_subtype"`
	MaxYield         int64         `json:"max_yield"`
	CurrentYield     int64         `json:"current_yield"`
	RegenerationRate sql.NullInt64 `json:"regeneration_rate"`
	SpawnedAt        sql.NullTime  `json:"spawned_at"`
	LastHarvest      sql.NullTime  `json:"last_harvest"`
	RespawnTimer     sql.NullTime  `json:"respawn_timer"`
	SpawnType        int64         `json:"spawn_type"`
	IsActive         sql.NullInt64 `json:"is_active"`
}
